name: Build
run-name: Testing build
on: [push]

jobs:
  build-for-android:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 3.24.5
    - run: flutter pub get
      working-directory: ./satellites
#    - run: flutter test
#      working-directory: ./satellites
    - run: flutter build apk
      working-directory: ./satellites
    - run: flutter build appbundle
      working-directory: ./satellites